spring.application.name=ApiTesting

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/QABotx}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:avanish7080}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}

history.retention-days=90