package com.example.ApiTesting.service;

import com.example.ApiTesting.entity.CollectionRun;
import org.springframework.stereotype.Service;


@Service
public class EmailTemplateServiceImpl implements EmailTemplateService {

    @Override
    public String buildExecutionReport(CollectionRun run) {

        String statusColor =
                run.getStatus().name().equals("COMPLETED")
                        ? "#28a745"
                        : "#dc3545";

        return """
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>

body{
    font-family:Arial,sans-serif;
    background:#f4f6f9;
    padding:30px;
}

.container{
    max-width:700px;
    margin:auto;
    background:white;
    border-radius:10px;
    overflow:hidden;
    box-shadow:0 2px 10px rgba(0,0,0,.15);
}

.header{
    background:#2563eb;
    color:white;
    padding:25px;
    text-align:center;
}

.title{
    font-size:28px;
    font-weight:bold;
}

.section{
    padding:25px;
}

table{
    width:100%%;
    border-collapse:collapse;
}

td{
    padding:10px;
    border-bottom:1px solid #eee;
}

.status{
    color:white;
    background:%s;
    padding:8px 18px;
    border-radius:20px;
    font-weight:bold;
}

.footer{
    padding:20px;
    background:#f8f9fa;
    text-align:center;
    color:#777;
    font-size:13px;
}

</style>
</head>

<body>

<div class="container">

<div class="header">

<div class="title">
API Testing Report
</div>

</div>

<div class="section">

<h2>Collection Execution Summary</h2>

<table>

<tr>
<td><b>Collection</b></td>
<td>%s</td>
</tr>

<tr>
<td><b>Status</b></td>
<td><span class="status">%s</span></td>
</tr>

<tr>
<td><b>Started</b></td>
<td>%s</td>
</tr>

<tr>
<td><b>Finished</b></td>
<td>%s</td>
</tr>

<tr>
<td><b>Total Requests</b></td>
<td>%d</td>
</tr>

<tr>
<td><b>Passed</b></td>
<td>%d</td>
</tr>

<tr>
<td><b>Failed</b></td>
<td>%d</td>
</tr>

<tr>
<td><b>Total Time</b></td>
<td>%d ms</td>
</tr>

</table>

</div>

<div class="footer">

Generated by API Testing Platform

</div>

</div>

</body>
</html>
"""
                .formatted(
                        statusColor,
                        run.getCollection().getName(),
                        run.getStatus(),
                        run.getStartedAt(),
                        run.getFinishedAt(),
                        run.getTotalRequests(),
                        run.getSuccessfulRequests(),
                        run.getFailedRequests(),
                        run.getTotalExecutionTime()
                );

    }
}
